In [122]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\karuna\appdata\local\programs\python\python312\lib\site-packages (1.7.1)
Requirement already satisfied: numpy>=1.22.0 in c:\users\karuna\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.2.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\karuna\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\karuna\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\karuna\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [87]:
#loading data
movies=pd.read_csv("tmdb_5000_movies.csv")
credits= pd.read_csv("tmdb_5000_credits.csv")

In [88]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [89]:
movies.shape

(4803, 20)

In [90]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [91]:
credits.shape

(4803, 4)

In [92]:
movies=movies.merge(credits,on='title')

In [93]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [94]:
''' id
overview
cast 
crew
title
keywords
genres'''

' id\noverview\ncast \ncrew\ntitle\nkeywords\ngenres'

In [95]:
movies=movies[['movie_id','title','overview', 'genres','keywords', 'cast', 'crew']]

In [96]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [97]:
import ast

In [98]:
def convert(text):
    L=[]
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [99]:
movies.dropna(inplace=True)

In [100]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [101]:
movies['genres']=movies['genres'].apply(convert)

In [102]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [103]:
movies['keywords']=movies['keywords'].apply(convert)

In [104]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [105]:
import ast

In [106]:
def convert3(text):
    L=[]
    counter=0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [107]:
movies['cast']=movies['cast'].apply(convert3)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [108]:
def director_name(text):
    L=[]
    for i in ast.literal_eval(text):
        if i['job']=='Director' :
            L.append(i['name'])
    return L

In [109]:
movies['crew']=movies['crew'].apply(director_name) 
movies.sample(7)

,movie_id,title,overview,genres,keywords,cast,crew
4247,30082,Forty Shades of Blue,A Russian woman living in Memphis with a much ...,"[Drama, Romance]",[independent film],"[Dina Korzun, Rip Torn, Darren E. Burrows]",[Ira Sachs]
594,3132,Bad Company,When a Harvard-educated CIA agent is killed du...,"[Action, Adventure, Comedy, Thriller]","[ambush, cia, assassin, nightclub, hustler, hi...","[Anthony Hopkins, Chris Rock, Peter Stormare]",[Joel Schumacher]
4388,39183,Once in a Lifetime: The Extraordinary Story of...,In the 1970s the North American Soccer League ...,[Documentary],"[new york, beckenbauer, pele]","[PelÃ©, Franz Beckenbauer, Carlos Alberto]","[Paul Crowder, John Dower]"
895,2123,"Me, Myself & Irene",Rhode Island State Trooper Charlie Baileygates...,[Comedy],"[schizophrenia, ex-cop, aftercreditsstinger, d...","[Jim Carrey, RenÃ©e Zellweger, Anthony Anderson]","[Bobby Farrelly, Peter Farrelly]"
910,9919,How to Lose a Guy in 10 Days,"An advice columnist, Andie Anderson (Kate Huds...","[Comedy, Romance]","[new york, bet, journalist, therapist, adverti...","[Kate Hudson, Matthew McConaughey, Kathryn Hahn]",[Donald Petrie]
3062,24034,Teacher's Pet,Spot (Lane) is a dog who can talk and read. Po...,"[Animation, Drama, Family, Music]",[],"[Nathan Lane, Kelsey Grammer, Shaun Fleming]",[Timothy Bjorklund]
3039,164558,One Direction: This Is Us,Go behind the scenes during One Directions sel...,"[Documentary, Music]",[concert],"[Harry Styles, Niall Horan, Zayn Malik]",[Morgan Spurlock]

In [110]:
def collapse(L):
    L1=[]
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [111]:
movies['crew']=movies['crew'].apply(collapse)
movies['cast']=movies['cast'].apply(collapse)
movies['keywords']=movies['keywords'].apply(collapse)
movies['genres']=movies['genres'].apply(collapse)

In [112]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [113]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [114]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [115]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."

In [116]:
new = movies.drop(columns=['overview','cast','crew','keywords','genres'])

In [117]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [119]:
new['tags']=new['tags'].apply(lambda x:" ".join(x))

In [120]:
new.head(2)

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."

In [123]:
#vectorization
from sklearn.feature_extraction.text import CountVectorizer
CV=CountVectorizer(max_features=5000, stop_words="english")

In [124]:
vector= CV.fit_transform(new['tags']).toarray()

In [126]:
vector.shape

(4805, 5000)

In [130]:
from sklearn.metrics.pairwise import cosine_similarity

In [131]:
similarity= cosine_similarity(vector)

In [132]:
similarity

array([[1.        , 0.08980265, 0.05986843, ..., 0.02431083, 0.02777778,
        0.        ],
       [0.08980265, 1.        , 0.06451613, ..., 0.02619813, 0.        ,
        0.        ],
       [0.05986843, 0.06451613, 1.        , ..., 0.02619813, 0.        ,
        0.        ],
       ...,
       [0.02431083, 0.02619813, 0.02619813, ..., 1.        , 0.0729325 ,
        0.04671418],
       [0.02777778, 0.        , 0.        , ..., 0.0729325 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04671418, 0.05337605,
        1.        ]], shape=(4805, 4805))

In [134]:
new[new['title']=='Avatar'].index[0]

np.int64(0)

In [142]:
sorted(list(enumerate(similarity[0])), reverse= True, key= lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (539, np.float64(0.25724787771376323)),
 (1192, np.float64(0.24873416908154544)),
 (260, np.float64(0.24759378423606915)),
 (1214, np.float64(0.24595492912420727)),
 (507, np.float64(0.24498947175305572)),
 (1916, np.float64(0.24019223070763068)),
 (582, np.float64(0.23809523809523808)),
 (1202, np.float64(0.23717082451262844)),
 (3728, np.float64(0.23570226039551587)),
 (74, np.float64(0.22360679774997894)),
 (1440, np.float64(0.22271770159368698)),
 (3606, np.float64(0.22075539284417395)),
 (322, np.float64(0.21919864974047634)),
 (83, np.float64(0.2187974872468418)),
 (4189, np.float64(0.2182178902359924)),
 (1533, np.float64(0.2166445612065605)),
 (2329, np.float64(0.21428571428571427)),
 (2405, np.float64(0.2135042050734495)),
 (47, np.float64(0.21339479988815996)),
 (61, np.float64(0.2132007163556104)),
 (495, np.float64(0.2132007163556104)),
 (972, np.float64(0.2130032168075646)),
 (942, np.float64(0.20953951903123735)),
 (466, np.float64(0.20851441405707477)),
 (1327, np.float64(0.20851441405707477)),
 (2200, np.float64(0.20309059861498083)),
 (973, np.float64(0.20008168266626025)),
 (1199, np.float64(0.19999999999999998)),
 (151, np.float64(0.19641855032959654)),
 (1273, np.float64(0.196116135138184)),
 (2782, np.float64(0.196116135138184)),
 (2969, np.float64(0.19364916731037085)),
 (4045, np.float64(0.19364916731037082)),
 (4404, np.float64(0.19245008972987526)),
 (36, np.float64(0.1917988185229168)),
 (3325, np.float64(0.1911797782254681)),
 (3536, np.float64(0.1892583246525563)),
 (305, np.float64(0.1889822365046136)),
 (3160, np.float64(0.18856180831641267)),
 (461, np.float64(0.18633899812498245)),
 (1319, np.float64(0.18633899812498245)),
 (150, np.float64(0.18605210188381271)),
 (931, np.float64(0.18569533817705186)),
 (27, np.float64(0.1849000654084097)),
 (2997, np.float64(0.1849000654084097)),
 (220, np.float64(0.18257418583505536)),
 (300, np.float64(0.18220272220337375)),
 (1069, np.float64(0.18220272220337375)),
 (67, np.float64(0.17960530202677488)),
 (301, np.float64(0.17928429140015906)),
 (4, np.float64(0.17791499872137212)),
 (184, np.float64(0.17791499872137212)),
 (373, np.float64(0.17766726362967533)),
 (46, np.float64(0.17407765595569785)),
 (7, np.float64(0.17391639824998364)),
 (2492, np.float64(0.17376201171422898)),
 (2727, np.float64(0.17376201171422898)),
 (1827, np.float64(0.17201561551404662)),
 (52, np.float64(0.1714985851425088)),
 (1342, np.float64(0.1714985851425088)),
 (149, np.float64(0.16933350266692065)),
 (26, np.float64(0.1690308509457033)),
 (1804, np.float64(0.1690308509457033)),
 (661, np.float64(0.16798421022632318)),
 (108, np.float64(0.16666666666666666)),
 (208, np.float64(0.16666666666666666)),
 (838, np.float64(0.16666666666666666)),
 (94, np.float64(0.16343011261515333)),
 (2511, np.float64(0.16343011261515333)),
 (1392, np.float64(0.1617875572323585)),
 (4007, np.float64(0.16169041669088863)),
 (31, np.float64(0.16037507477489604)),
 (581, np.float64(0.16037507477489604)),
 (1295, np.float64(0.16012815380508713)),
 (1379, np.float64(0.16012815380508713)),
 (4335, np.float64(0.16012815380508713)),
 (168, np.float64(0.15811388300841897)),
 (91, np.float64(0.15748519708717798)),
 (3626, np.float64(0.15474611514754322)),
 (311, np.float64(0.15430334996209188)),
 (1961, np.float64(0.15319083833634298)),
 (577, np.float64(0.15214515486254612)),
 (3352, np.float64(0.15214515486254612)),
 (158, np.float64(0.15075567228888181)),
 (502, np.float64(0.15075567228888181)),
 (1353, np.float64(0.15075567228888181)),
 (111, np.float64(0.1496710850223124)),
 (1176, np.float64(0.1496710850223124)),
 (2165, np.float64(0.1496710850223124)),
 (172, np.float64(0.14907119849998596)),
 (490, np.float64(0.14907119849998596)),
 (17, np.float64(0.1481668148335556)),
 (1934, np.float64(0.1474419561548971)),
 (422, np.float64(0.14547859349066158)),
 (505, np.float64(0.14547859349066158)),
 (1484, np.float64(0.14547859349066158)),
 (557, np.float64(0.14506471329641488)),
 (41, np.float64(0.14433756729740646)),
 (84, np.float64(0.14360673947588817)),
 (332, np.float64(0.14291548761875733)),
 (568, np.float64(0.14291548761875733)),
 (2682, np.float64(0.14291548761875733)),
 (56, np.float64(0.14213381090374028)),
 (249, np.float64(0.14213381090374028)),
 (1325, np.float64(0.14213381090374028)),
 (2580, np.float64(0.14213381090374028)),
 (1320, np.float64(0.1414213562373095)),
 (1218, np.float64(0.14085904245475275)),
 (487, np.float64(0.13900960937138318)),
 (187, np.float64(0.1388888888888889)),
 (413, np.float64(0.1388888888888889)),
 (1669, np.float64(0.1386750490563073)),
 (2476, np.float64(0.1386750490563073)),
 (4347, np.float64(0.1386750490563073)),
 (2869, np.float64(0.13867504905630726)),
 (2129, np.float64(0.13736056394868904)),
 (1941, np.float64(0.13699915608779772)),
 (1829, np.float64(0.13608276348795434)),
 (2616, np.float64(0.13608276348795434)),
 (4489, np.float64(0.13608276348795434)),
 (595, np.float64(0.13518451760896877)),
 (1013, np.float64(0.13518451760896877)),
 (3407, np.float64(0.13518451760896877)),
 (3620, np.float64(0.13518451760896877)),
 (342, np.float64(0.13471506281091267)),
 (127, np.float64(0.1338258447578277)),
 (754, np.float64(0.13344012817090595)),
 (1475, np.float64(0.13344012817090595)),
 (68, np.float64(0.13333333333333333)),
 (134, np.float64(0.13333333333333333)),
 (368, np.float64(0.13333333333333333)),
 (1156, np.float64(0.13333333333333333)),
 (2968, np.float64(0.13333333333333333)),
 (3671, np.float64(0.13176156917368248)),
 (1000, np.float64(0.13130643285972254)),
 (1045, np.float64(0.13074409009212268)),
 (1094, np.float64(0.13074409009212268)),
 (1654, np.float64(0.13074409009212268)),
 (2374, np.float64(0.13074409009212268)),
 (3374, np.float64(0.13074409009212268)),
 (3996, np.float64(0.13074409009212268)),
 (740, np.float64(0.1301448015738384)),
 (529, np.float64(0.12858612496840993)),
 (778, np.float64(0.12858612496840993)),
 (1297, np.float64(0.12858612496840993)),
 (1613, np.float64(0.12858612496840993)),
 (483, np.float64(0.12830005981991682)),
 (420, np.float64(0.1270821419438372)),
 (1035, np.float64(0.1270821419438372)),
 (238, np.float64(0.1259881576697424)),
 (939, np.float64(0.1259881576697424)),
 (1737, np.float64(0.1259881576697424)),
 (1743, np.float64(0.1259881576697424)),
 (278, np.float64(0.1256297269074015)),
 (2709, np.float64(0.1256297269074015)),
 (3307, np.float64(0.1256297269074015)),
 (1711, np.float64(0.125)),
 (3216, np.float64(0.125)),
 (432, np.float64(0.12422599874998833)),
 (228, np.float64(0.12422599874998831)),
 (28, np.float64(0.12379689211803457)),
 (1272, np.float64(0.12379689211803457)),
 (4672, np.float64(0.12379689211803457)),
 (95, np.float64(0.12286829679574761)),
 (454, np.float64(0.1228682967957476)),
 (549, np.float64(0.1228682967957476)),
 (50, np.float64(0.1217161238900369)),
 (72, np.float64(0.1217161238900369)),
 (275, np.float64(0.1217161238900369)),
 (579, np.float64(0.1217161238900369)),
 (1978, np.float64(0.1217161238900369)),
 (2071, np.float64(0.1217161238900369)),
 (2864, np.float64(0.1217161238900369)),
 (1508, np.float64(0.1215541595815788)),
 (2543, np.float64(0.12155415958157878)),
 (624, np.float64(0.12126781251816647)),
 (653, np.float64(0.12126781251816647)),
 (808, np.float64(0.12126781251816647)),
 (1571, np.float64(0.12126781251816647)),
 (3145, np.float64(0.1203858530857692)),
 (687, np.float64(0.11973686801784994)),
 (123, np.float64(0.11904761904761904)),
 (692, np.float64(0.11904761904761904)),
 (1275, np.float64(0.11904761904761904)),
 (3405, np.float64(0.11904761904761904)),
 (3628, np.float64(0.11904761904761904)),
 (169, np.float64(0.11785113019775792)),
 (1570, np.float64(0.11785113019775792)),
 (166, np.float64(0.1178511301977579)),
 (232, np.float64(0.1178511301977579)),
 (294, np.float64(0.1178511301977579)),
 (859, np.float64(0.1178511301977579)),
 (1612, np.float64(0.1178511301977579)),
 (5, np.float64(0.11669000700233413)),
 (206, np.float64(0.11669000700233413)),
 (10, np.float64(0.1160517706371319)),
 (87, np.float64(0.1160517706371319)),
 (1029, np.float64(0.1160517706371319)),
 (2579, np.float64(0.1160517706371319)),
 (3006, np.float64(0.1160517706371319)),
 (81, np.float64(0.11547005383792512)),
 (627, np.float64(0.11470786693528086)),
 (1369, np.float64(0.11470786693528086)),
 (2255, np.float64(0.11470786693528086)),
 (2319, np.float64(0.11470786693528086)),
 (3719, np.float64(0.11470786693528086)),
 (3997, np.float64(0.11470786693528086)),
 (199, np.float64(0.11446713662390752)),
 (14, np.float64(0.11433239009500587)),
 (126, np.float64(0.11433239009500587)),
 (508, np.float64(0.11433239009500587)),
 (1193, np.float64(0.11433239009500587)),
 (777, np.float64(0.11340230290662862)),
 (854, np.float64(0.1126872339638022)),
 (900, np.float64(0.1126872339638022)),
 (2446, np.float64(0.1126872339638022)),
 (3496, np.float64(0.1126872339638022)),
 (35, np.float64(0.11180339887498947)),
 (141, np.float64(0.11180339887498947)),
 (325, np.float64(0.11180339887498947)),
 (1520, np.float64(0.11180339887498947)),
 (1717, np.float64(0.11180339887498947)),
 (1723, np.float64(0.11180339887498947)),
 (2630, np.float64(0.11180339887498947)),
 (4015, np.float64(0.11180339887498947)),
 (4132, np.float64(0.11180339887498947)),
 (4200, np.float64(0.11180339887498947)),
 (18, np.float64(0.11135885079684349)),
 (1493, np.float64(0.11135885079684349)),
 (2102, np.float64(0.11135885079684349)),
 (2435, np.float64(0.11135885079684349)),
 (513, np.float64(0.1111111111111111)),
 (1080, np.float64(0.1111111111111111)),
 (1292, np.float64(0.1111111111111111)),
 (2009, np.float64(0.1111111111111111)),
 (3338, np.float64(0.1111111111111111)),
 (3618, np.float64(0.1111111111111111)),
 (4094, np.float64(0.1111111111111111)),
 (102, np.float64(0.11037769642208699)),
 (1017, np.float64(0.11037769642208699)),
 (2756, np.float64(0.11037769642208699)),
 (131, np.float64(0.10959932487023819)),
 (174, np.float64(0.10959932487023819)),
 (266, np.float64(0.10959932487023819)),
 (312, np.float64(0.10959932487023819)),
 (330, np.float64(0.10959932487023819)),
 (2068, np.float64(0.10959932487023819)),
 (3100, np.float64(0.10959932487023819)),
 (4076, np.float64(0.10959932487023819)),
 (403, np.float64(0.10942202738310211)),
 (3053, np.float64(0.1091089451179962)),
 (3779, np.float64(0.1091089451179962)),
 (773, np.float64(0.10910894511799618)),
 (1154, np.float64(0.10910894511799618)),
 (3659, np.float64(0.10910894511799618)),
 (3951, np.float64(0.10910894511799618)),
 (239, np.float64(0.10849075915068655)),
 (295, np.float64(0.10814761408717502)),
 (535, np.float64(0.10814761408717502)),
 (2177, np.float64(0.10814761408717502)),
 (986, np.float64(0.10675210253672475)),
 (4227, np.float64(0.10675210253672475)),
 (139, np.float64(0.10669739994407998)),
 (4544, np.float64(0.10669739994407998)),
 (105, np.float64(0.10660035817780521)),
 (233, np.float64(0.10660035817780521)),
 (476, np.float64(0.10660035817780521)),
 (2452, np.float64(0.10660035817780521)),
 (2517, np.float64(0.10660035817780521)),
 (2558, np.float64(0.10660035817780521)),
 (2758, np.float64(0.10660035817780521)),
 (3837, np.float64(0.10660035817780521)),
 (4195, np.float64(0.10660035817780521)),
 (182, np.float64(0.10540925533894598)),
 (334, np.float64(0.10540925533894598)),
 (1054, np.float64(0.10540925533894598)),
 (3781, np.float64(0.10540925533894598)),
 (33, np.float64(0.10425720702853739)),
 (85, np.float64(0.10425720702853739)),
 (148, np.float64(0.10425720702853739)),
 (715, np.float64(0.10425720702853739)),
 (935, np.float64(0.10425720702853739)),
 (1278, np.float64(0.10425720702853739)),
 (1497, np.float64(0.10425720702853739)),
 (2656, np.float64(0.10425720702853739)),
 (4330, np.float64(0.10425720702853739)),
 (129, np.float64(0.10411584125907071)),
 (510, np.float64(0.10411584125907071)),
 (643, np.float64(0.10411584125907071)),
 (898, np.float64(0.10411584125907071)),
 (1084, np.float64(0.10411584125907071)),
 (1107, np.float64(0.10411584125907071)),
 (3462, np.float64(0.10411584125907071)),
 (307, np.float64(0.10314212462587934)),
 (279, np.float64(0.10286889997472794)),
 (1231, np.float64(0.10286889997472794)),
 (1271, np.float64(0.10286889997472794)),
 (3441, np.float64(0.10286889997472794)),
 (4042, np.float64(0.10286889997472794)),
 (2592, np.float64(0.10286889997472792)),
 (157, np.float64(0.10206207261596575)),
 (263, np.float64(0.10206207261596575)),
 (400, np.float64(0.10206207261596575)),
 (660, np.float64(0.10206207261596575)),
 (781, np.float64(0.10206207261596575)),
 (1299, np.float64(0.10206207261596575)),
 (1938, np.float64(0.10206207261596575)),
 (2657, np.float64(0.10206207261596575)),
 (4253, np.float64(0.10206207261596575)),
 (4622, np.float64(0.10206207261596575)),
 (371, np.float64(0.10166571355506977)),
 (412, np.float64(0.10166571355506977)),
 (473, np.float64(0.10166571355506977)),
 (870, np.float64(0.10166571355506977)),
 (1200, np.float64(0.10166571355506977)),
 (1435, np.float64(0.10166571355506977)),
 (270, np.float64(0.10050378152592121)),
 (410, np.float64(0.10050378152592121)),
 (813, np.float64(0.10050378152592121)),
 (933, np.float64(0.10050378152592121)),
 (1274, np.float64(0.10050378152592121)),
 (1819, np.float64(0.10050378152592121)),
 (1842, np.float64(0.10050378152592121)),
 (1999, np.float64(0.10050378152592121)),
 (2280, np.float64(0.10050378152592121)),
 (292, np.float64(0.1)),
 (389, np.float64(0.1)),
 (530, np.float64(0.1)),
 (920, np.float64(0.1)),
 (1075, np.float64(0.1)),
 (2647, np.float64(0.1)),
 (3091, np.float64(0.1)),
 (3734, np.float64(0.1)),
 (1087, np.float64(0.09960238411119947)),
 (243, np.float64(0.09829463743659808)),
 (785, np.float64(0.09820927516479827)),
 (142, np.float64(0.09805806756909201)),
 (564, np.float64(0.09805806756909201)),
 (791, np.float64(0.09805806756909201)),
 (1404, np.float64(0.09805806756909201)),
 (1470, np.float64(0.09805806756909201)),
 (1585, np.float64(0.09805806756909201)),
 (1682, np.float64(0.09805806756909201)),
 (1752, np.float64(0.09805806756909201)),
 (589, np.float64(0.09724332766526303)),
 (1355, np.float64(0.09724332766526303)),
 (43, np.float64(0.09622504486493763)),
 (618, np.float64(0.09622504486493763)),
 (2484, np.float64(0.09622504486493763)),
 (2792, np.float64(0.09622504486493763)),
 (3152, np.float64(0.09622504486493763)),
 (12, np.float64(0.09622504486493762)),
 (122, np.float64(0.09622504486493762)),
 (236, np.float64(0.09622504486493762)),
 (362, np.float64(0.09622504486493762)),
 (2089, np.float64(0.09622504486493762)),
 (2392, np.float64(0.09622504486493762)),
 (2648, np.float64(0.09622504486493762)),
 (160, np.float64(0.09558988911273406)),
 (1414, np.float64(0.09523809523809523)),
 (23, np.float64(0.0944911182523068)),
 (511, np.float64(0.0944911182523068)),
 (922, np.float64(0.0944911182523068)),
 (1025, np.float64(0.0944911182523068)),
 (1304, np.float64(0.0944911182523068)),
 (2836, np.float64(0.0944911182523068)),
 (3426, np.float64(0.0944911182523068)),
 (479, np.float64(0.09435641951204964)),
 (1920, np.float64(0.09428090415820634)),
 (596, np.float64(0.09335200560186731)),
 (1276, np.float64(0.09335200560186731)),
 (1828, np.float64(0.09335200560186731)),
 (21, np.float64(0.09284766908852593)),
 (242, np.float64(0.09284766908852593)),
 (306, np.float64(0.09284766908852593)),
 (691, np.float64(0.09284766908852593)),
 (794, np.float64(0.09284766908852593)),
 (901, np.float64(0.09284766908852593)),
 (960, np.float64(0.09284766908852593)),
 (978, np.float64(0.09284766908852593)),
 (1002, np.float64(0.09284766908852593)),
 (1247, np.float64(0.09284766908852593)),
 (4467, np.float64(0.09284766908852593)),
 (799, np.float64(0.09259259259259259)),
 (2270, np.float64(0.09245003270420485)),
 (2384, np.float64(0.09245003270420485)),
 (2852, np.float64(0.09245003270420485)),
 (4352, np.float64(0.09245003270420485)),
 (4501, np.float64(0.09245003270420485)),
 (4515, np.float64(0.09245003270420485)),
 (4653, np.float64(0.09245003270420485)),
 (1492, np.float64(0.09157370929912602)),
 (2444, np.float64(0.09147021665807528)),
 (75, np.float64(0.09128709291752768)),
 (112, np.float64(0.09128709291752768)),
 (164, np.float64(0.09128709291752768)),
 (227, np.float64(0.09128709291752768)),
 (315, np.float64(0.09128709291752768)),
 (349, np.float64(0.09128709291752768)),
 (356, np.float64(0.09128709291752768)),
 (369, np.float64(0.09128709291752768)),
 (626, np.float64(0.09128709291752768)),
 (1374, np.float64(0.09128709291752768)),
 (1696, np.float64(0.09128709291752768)),
 (1786, np.float64(0.09128709291752768)),
 (3447, np.float64(0.09128709291752768)),
 (3535, np.float64(0.09128709291752768)),
 (3814, np.float64(0.09128709291752768)),
 (4625, np.float64(0.09128709291752768)),
 (107, np.float64(0.09072184232530289)),
 (170, np.float64(0.09072184232530289)),
 (812, np.float64(0.09072184232530289)),
 (2001, np.float64(0.09072184232530289)),
 (2966, np.float64(0.09072184232530289)),
 (32, np.float64(0.08989331499509895)),
 (45, np.float64(0.08989331499509895)),
 (222, np.float64(0.08989331499509895)),
 (491, np.float64(0.08989331499509895)),
 (541, np.float64(0.08989331499509895)),
 (2494, np.float64(0.08989331499509895)),
 (1, np.float64(0.08980265101338746)),
 (88, np.float64(0.08980265101338746)),
 (121, np.float64(0.08980265101338746)),
 (245, np.float64(0.08980265101338746)),
 (775, np.float64(0.08980265101338746)),
 (894, np.float64(0.08980265101338746)),
 (937, np.float64(0.08980265101338746)),
 (2163, np.float64(0.08980265101338746)),
 (3299, np.float64(0.08980265101338746)),
 (363, np.float64(0.0890870806374748)),
 (381, np.float64(0.0890870806374748)),
 (467, np.float64(0.0890870806374748)),
 (2876, np.float64(0.0890870806374748)),
 (4736, np.float64(0.0890870806374748)),
 (2382, np.float64(0.08883363181483767)),
 (86, np.float64(0.08838834764831843)),
 (96, np.float64(0.08838834764831843)),
 (98, np.float64(0.08838834764831843)),
 (241, np.float64(0.08838834764831843)),
 (547, np.float64(0.08838834764831843)),
 (1111, np.float64(0.08838834764831843)),
 (2243, np.float64(0.08838834764831843)),
 (2247, np.float64(0.08838834764831843)),
 (2300, np.float64(0.08838834764831843)),
 (2790, np.float64(0.08838834764831843)),
 (3089, np.float64(0.08838834764831843)),
 (4256, np.float64(0.08838834764831843)),
 (4656, np.float64(0.08838834764831843)),
 (230, np.float64(0.08830215713766959)),
 (654, np.float64(0.08830215713766959)),
 (1280, np.float64(0.08830215713766959)),
 (1874, np.float64(0.08830215713766959)),
 (103, np.float64(0.08753762190648169)),
 (3439, np.float64(0.08753762190648169)),
 (39, np.float64(0.08703882797784893)),
 (101, np.float64(0.08703882797784893)),
 (203, np.float64(0.08703882797784893)),
 (457, np.float64(0.08703882797784893)),
 (786, np.float64(0.08703882797784893)),
 (814, np.float64(0.08703882797784893)),
 (899, np.float64(0.08703882797784893)),
 (1140, np.float64(0.08703882797784893)),
 (1205, np.float64(0.08703882797784893)),
 (1469, np.float64(0.08703882797784893)),
 (1519, np.float64(0.08703882797784893)),
 (2813, np.float64(0.08703882797784893)),
 (3233, np.float64(0.08703882797784893)),
 (193, np.float64(0.08679260732054925)),
 (501, np.float64(0.08679260732054925)),
 (1824, np.float64(0.08679260732054925)),
 (1617, np.float64(0.08606629658238703)),
 (2161, np.float64(0.08606629658238703)),
 (2246, np.float64(0.08606629658238703)),
 (2335, np.float64(0.08606629658238703)),
 (3067, np.float64(0.08606629658238703)),
 (4162, np.float64(0.08606629658238703)),
 (4491, np.float64(0.08606629658238703)),
 (4717, np.float64(0.08606629658238703)),
 (70, np.float64(0.08574929257125441)),
 (257, np.float64(0.08574929257125441)),
 (746, np.float64(0.08574929257125441)),
 (1159, np.float64(0.08574929257125441)),
 (1267, np.float64(0.08574929257125441)),
 (3026, np.float64(0.08574929257125441)),
 (3138, np.float64(0.08574929257125441)),
 (3308, np.float64(0.08574929257125441)),
 (3387, np.float64(0.08574929257125441)),

In [145]:
#main function 
def recommend(movie):
    index=new[new['title']==movie].index[0]
    movie_list= sorted(list(enumerate(similarity[index])), reverse= True, key= lambda x:x[1])[1:6]
    for i in movie_list:
        print(new.iloc[i[0]].title)

In [144]:
#new.iloc[539].title

movie_id                                                 7450
title                                              Titan A.E.
tags        A young man finds out that he holds the key to...
Name: 539, dtype: object

In [146]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Aliens vs Predator: Requiem
Independence Day

In [147]:
import pickle

In [148]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [152]:
movies['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], shape=(4805,), dtype=object)